#%RAML 1.0
title: product-API
baseUri: http://localhost:8081/products
/products:
  get:
    description: To get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID": "1234",
                "productName": "Chinna Mule course",
                "productOwner": "Chinna",
                "productDescription": "complete Mule Developer"
              }

